<div class="jumbotron">
    <h1>
        Edit
    </h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->render('application/index/form', array(
            'form'  => $this->form,
            'route' => $this->url($this->currentRoute(null, true), array(
                'id' => $this->data->id
            )),
            'readonly' => $this->readonly
        )); ?>
    </div>
</div>