<div class="jumbotron">
    <h1>
        Tags
    </h1>
</div>

<div class="row">
    <div class="col-lg-6 col-md-6">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-lg-10">Tag</th>
                    <th class="col-lg-2">Url Count</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->data as $tag) : ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->url('tag', array(
                                'slug' => $tag['slug']
                            )); ?>"> <?php echo $this->escapeHtml($tag['name']); ?></a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($tag['tag_count']); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>